### ISSUE TITLE
using macro to construct the partial statement

### ISSUE THREAD

**Issue by beenotung** [mistlog/typedraft#18]
I want to use macro to do type-safe code generation. As my understanding, typedraft only supports inlining one/many typescript statement but it cannot inline part of a statement.

Target Code:
```typescript
export class CoreService {
  Call<C extends Call>(args: CallInput<C>): Result<C['Out']> {
    const { CallType, Type, In } = args
    const _type = Type as Call['Type']
    let method: (In: C['In']) => C['Out']
    switch (_type) {
      case 'CancelSubscribe':
        // @ts-ignore
        method = this.CancelSubscribe
        break
      case 'SetKV':
        // @ts-ignore
        method = this.SetKV
        break
      case 'DeleteByKey':
        // @ts-ignore
        method = this.DeleteByKey
        break
      ...
  }
}
```
Where the list of cases should be generated from an array.

That is not possible to be done in current syntax, because the 'context function' are consist of complete typescript/tsx statement.
Even when I tried to use a chain of if, it's not possible.

```tsx
function Name(props: { name: string }) {
  return props.name
}

function IfCall(props: { type: string, call: (typeof calls)[number] }) {
  if (props.call.Type === props.type) {
    method = this.<Name name={props.type}/>
  }
}

function SwitchCall(props: { type: string }) {
  for (let call of calls) {
    <IfCall call={call} type={props.type}/>
  }
}
```

It will complain about syntax error at the `this.<Name .../>;` with error message like `SyntaxError: Unexpected token (30:9)`

I know it can make a working version by accessing the code with key-ed method, like `let method: (In: C['In']) => C['Out'] = this[_type]` but this would not work until we use `as any`, which lose the type checking

**Comment by mistlog** [comment]
The reason is that `this.<Name name={props.type}/>` is invalid, as typedraft only supports macro used as **standalone** JSX element:

```ts
//  standalone, a single statement that contains only JSX element
<Context/>;
...
function Context() {...}
```

By the way, props is redundant in `<IfCall ...>`:

```diff
- <IfCall call={call} type={props.type}/>
+//@ts-ignore
+ <IfCall/>
```

# Solution

> Where the list of cases should be generated from an array.

We can use a DSL to generate code, the input of your code maybe something like this:

```ts
export class CoreService {
    Call<C extends Call>(args: CallInput<C>): Result<C['Out']> {
        const { CallType, Type, In } = args
        const _type = Type as Call['Type']
        let method: (In: C['In']) => C['Out']
        {
            "use match";
            ["CancelSubscribe", "SetKV", "DeleteByKey"].map(_type => method = this[_type]);
        }
    }
}
```
and the result will be exactly:

```ts
export class CoreService {
  Call<C extends Call>(args: CallInput<C>): Result<C['Out']> {
    const {
      CallType,
      Type,
      In
    } = args;

    const _type = (Type as Call['Type']);

    let method: (In: C['In']) => C['Out'];

    switch (_type) {
      case "CancelSubscribe":
        method = this.CancelSubscribe;
        break;

      case "SetKV":
        method = this.SetKV;
        break;

      case "DeleteByKey":
        method = this.DeleteByKey;
        break;
    }
  }
}
```

You don't have type check in typedraft, however, you finally have it in the generated code(typescript). 

This demo project can be found in https://github.com/mistlog/dsl-debug-demo/tree/typedraft/issues/18. 

Run these commands and the result will be `src/demo.ts`:

```shell
npm install
npm run build
```

For DSL related, see https://mistlog.github.io/typedraft-docs/docs/implement-a-dsl
For JSX as Macro, see https://mistlog.github.io/typedraft-docs/docs/jsx-as-macro

**Comment by beenotung** [comment]
The match DSL in your example is a clear teaching material for manipulating bable AST with typedraft helper functions.
Really appreciate your timely helpful response
